# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as two services called "todo-app" and “todo-database”
# The service “todo-app” is built from the Dockerfile in the /app directory,
# and the service “todo-database” uses the official MongoDB image 
# from Docker Hub - https://hub.docker.com/_/mongo. 
# You can add other services your application may depend on here.

services:
  mcat-scraper-frontend:
    build:
      context: ./mcat-scraper-app
    # volumes: 
    #  - ./mcat-scraper-app:/usr/src/app
    #  - /usr/src/app/node_modules
    ports:
      - 3002:5173

  mcat-scraper-database:
    image: mongo:6
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - mcat-scraper-database:/data/db

  mcat-scraper-api:
    build:
      context: ./mcat-scraper-api
    depends_on:
      - mcat-scraper-database
    links:
      - mcat-scraper-database
    ports:
      - 3003:8080
    
  mcat-scraper-scrap-container:
    build:
      context: ./scraper
    depends_on:
      - mcat-scraper-database
    links:
      - mcat-scraper-database
    volumes:
      - ./scraper:/usr/src/scraper
      - /usr/src/scraper/node_modules

networks:
  default:
    name: mcat-scraper

volumes:
  mcat-scraper-database:
    name: "mcat-scraper-database"
    